### ISSUE TITLE
Suggestion: Fishsticks needs The Nod

### ISSUE THREAD

**Issue by NeoJabez** [SkyeRangerDelta/Fishsticks#12]
An echo announcement was made, and someone noticed that the bot yelled at itself for not having The Nod. I gave it The Nod, but then removed it, worried that it could break something. Report on Discord in bot-logger channel.

**Comment by SkyeRangerDelta** [comment]
Role changes are approved with my prior consent, but most are completely fine. thanks for the note, but you can just DM me next time. lol.
