### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by NeoJabez** [SkyeRangerDelta/Fishsticks#13]
A Suggestions channel filled by the adding of a word trigger command with a syntax like:

!suggest my suggestion

would result in everything typed after the trigger being deposited in a locked down Suggestions channel. @everyone would have access to read messages and message history in this channel, and perhaps add reactions to suggestions made, but otherwise would have no ability to discuss anything in this channel, keeping it clean and easy to follow.

This would streamline the suggestions system for Fishsticks, and not require people to use the github issues system for this purpose, instead suggesting directly on the server itself.

If abused, the suggestions channel could only be visible to leadership or moderators and above, rather than the public or @everyone. I suggest @everyone because if adding reactions is allowed, people could immediately thumbs up or thumbs down suggestions on the fly.

**Comment by SkyeRangerDelta** [comment]
I like this. I can streamline this as well in development.

You got it. V17 it comes.

**Comment by SkyeRangerDelta** [comment]
Done! Fine tuning may be worked out, but the gist is there and works fantastically.

Syntax:
`!suggest -[Suggestion Title] -[Suggestion Body]`

Parameters: spaces permitted
Suggestion Title: The title of the issue being opened (ie; email subject line)
Suggestion Body: Whatever your suggestion is. Only limited by Discord's message capability.

Handling is done via Zapier webhook - however I may be moving this over to the GitHub API for instantaneous results and removal of 3rd party systems.

Command is tied into FishsticksOnline as "Suggestions Offered".
