### ISSUE TITLE
Remindme Command

### ISSUE THREAD

**Issue by FishsticksCC** [SkyeRangerDelta/Fishsticks#24]
A command that pings you with a customizable message after a set time.  Kinda like echo, but only for yourself.  Suggested syntax of `!remindme

**Comment by SkyeRangerDelta** [comment]
For reference, proposed syntax: `!remindme -[timeInMinutes] -[messageToBeReminded]`

**Comment by SkyeRangerDelta** [comment]
V1.17.3 Adds this command, closing.
