### ISSUE TITLE
Dictionary Functionality

### ISSUE THREAD

**Issue by FishsticksCC** [SkyeRangerDelta/Fishsticks#34]
Maybe we could have a command that looks up definitions from dictionary.com or somewhere similar? What's one more API, SKYE?!?!?

**Comment by SkyeRangerDelta** [comment]
I'll take that challenge.
Probably going to crank from here: https://developer.oxforddictionaries.com/

**Comment by SkyeRangerDelta** [comment]
Definitions have been implemented via the Oxford University Dictionary API. Up to 4 definitions of a word will be displayed in a non-deleting embed.
