### ISSUE TITLE
TITLE

### ISSUE THREAD

**Issue by FishsticksCC** [SkyeRangerDelta/Fishsticks#36]
Commands like role list and help delete too fast.  Id suggest upping the timer to 5 minutes for both.

**Comment by SkyeRangerDelta** [comment]
No, 5 minutes is far too long.

But you do get a time increase.
`!roles`: Game role embed increased to 1m 15s, divisions increased to 45s, regular cc roles increased to 45s.
`!role`:  Game role embed increased to 1m 15s, divisions increased to 45s.
`!help`: You can't look through it in 45 seconds? Very well, increased to 1m.

If this persists to be a problem, let me know. These changes will role out next update.
