### ISSUE TITLE
sass mode

### ISSUE THREAD

**Issue by FishsticksCC** [SkyeRangerDelta/Fishsticks#57]
keep standard error messages as default, let users opt in to sass mode for sarcasm with side of error messages.

**Comment by SkyeRangerDelta** [comment]
So, follow up question - this looks like it's requesting a per user sarcastic response - which is very complex to do.

As it stands, the current method is to deploy the sarcastic response with the error message immediately following it. Like, you're not going to just get a load of "you're terrible at what you do" without telling you what you did wrong. And even then, you'd need to actually trigger one.

Is the per user thing still the intention?

**Comment by SkyeRangerDelta** [comment]
No need, most errors/responses are no longer inherently rude or are otherwise visibly sarcastic.
