### ISSUE TITLE
Shiny

### ISSUE THREAD

**Issue by FishsticksCC** [SkyeRangerDelta/Fishsticks#58]
Have a 1/8192 chance for a message's text to show up as either a different font or different color with a message alongside it

**Comment by SkyeRangerDelta** [comment]
I want to implement this, but due to the Discord API - it's not possible to do specifically what this wants.

I can however make it appear to be as stated using Canvas to create a mimic message that's actually an image or similar, however.

**Comment by SkyeRangerDelta** [comment]
I think I did it. I don't know for sure, but I guess we'll find out.
