### ISSUE TITLE
Suggestion: Standardize Parameter Notation

### ISSUE THREAD

**Issue by Gman217** [SkyeRangerDelta/Fishsticks#6]
Since the introduction of the new role commands in v16, there has been some minor inconsistency in how parameters are called.  Some commands take flat words as parameters. Some commands need - as a parameter precursor.  I recommend we switch all active commands to take - as a precursor, in order to develop a more natural habit to avoid confusing users.

**Comment by SkyeRangerDelta** [comment]
The documentation has been built around the presence of this and may be changed later. Not all commands require it and therefore don't use it because its easier to formulate commands without the use of a hypen. They are only used when multiple parameters need spaces in them.

**Comment by Gman217** [comment]
My point was that whether they require it or not, having all commands formed/formatted the same way improves the user experience.  If I am in the habit of separating parameters with spaces, it becomes difficult to remember to separate parameters with a - on the ones that require it.  This means that often the first attempt results in frequent failure on the first attempt, which increases frustration and drives down enthusiastic adoption.  Humans are creatures of habit.  If all commands adopt the same format, habits formed work in favor of the user, rather than against the user.

**Comment by SkyeRangerDelta** [comment]
Lol, you've used linux command line before right?

Commands with spaces will still work if you use hypens interestingly enough. However, as you've seen, this topic is on the backburner as it's not a prime concern, but the dilemma is noted.

**Comment by Gman217** [comment]
Oh for sure.  I'm not trying to have this prioritized inappropriately, just that this should be in the mix.

Because, as you well know, just because I've used the Linux command line before, does not mean all of your userbase has.  And you shouldn't be building only for Linux nerds. :p

**Comment by SkyeRangerDelta** [comment]
As per the recent Fishsticks inquiry survey - I'm moving to implement this issue as I finally have (while not overly decisive) an answer.

There's a solid divide between using spaces, hyphens, or a mix to properly use Fishsticks; but the survey results have stated that hyphens are the way to go.

![image](https://user-images.githubusercontent.com/12277949/84466722-0af9fe80-ac48-11ea-9e33-2d9e5da032ff.png)

**Comment by SkyeRangerDelta** [comment]
Command handling is now using hyphens as standard notation. All parameters are differentiated by hyphens.
