### ISSUE TITLE
Suggestion: Role vs Roles

### ISSUE THREAD

**Issue by SilverHoudini** [SkyeRangerDelta/Fishsticks#7]
It's confusing on the difference between the two. Is there a way to makes it less confusing? Ie one is ServerRoles and one is GameRoles? Again, I know literally nothing about coding, so if it's not simple, I likely don't understand it. I doubt I'm alone in this.

**Comment by SkyeRangerDelta** [comment]
Likely going to work on this. `!roles` is easier to run than `!role -list` is.

> Card added to V16 - P2 to add an embed that shows game roles under the `!roles` command. `!role -list` will still only show game roles.

**Comment by SkyeRangerDelta** [comment]
Queued for V17.

**Comment by SkyeRangerDelta** [comment]
Actively working on.

**Comment by SkyeRangerDelta** [comment]
Done.
