### ISSUE TITLE
Request for Peristent !vouch notification messages

### ISSUE THREAD

**Issue by Kesarahk** [SkyeRangerDelta/Fishsticks#8]
Staff can't easily see whether a new join has received 2 vouches since the !vouch notification messages auto-delete. 
This is a request to make the !vouch notification messages persistent so staff can easily see the vouch history of a new join, without receiving the "You're dumb!" treatment from our lovely bot Fishsticks. ^^

Thank you for your time!

**Comment by SkyeRangerDelta** [comment]
Pertinent messages such as: "granting recognized" and "they need one more vouch" are now perma-messages. All other vouch-related messages are still self-deleting for spam cleanup.
