### ISSUE TITLE
idea for the prayer docket

### ISSUE THREAD

**Issue by SkyeRangerDelta** [SkyeRangerDelta/Fishsticks#88]
idea to have a pinned message in <

**Comment by AJman14** [comment]
Lol, so no channel tags in suggestions. Original post:
**Idea for the Prayer docket: Have a pinned message in #prayer-requests that Fs updates when docket items are added/removed?**

**Comment by SkyeRangerDelta** [comment]
>> When docket is cleared, remove the pin to prevent future use/pins covering up the docket. Recreate the pin (and subsequently add to top of pins) when a new docket point is added.

**Comment by SkyeRangerDelta** [comment]
Fixed in https://github.com/SkyeRangerDelta/Fishsticks/commit/2cd6685d4c93157f56c4e63d5c7dea4106c61b1f
